# Generated by Django 6.1 on 2026-09-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='otp',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
